name: Deploy to EdgeOne Pages
on:
  push:
    branches: [master]
    paths:
      - 'apps/mobile_web/web/edge-functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EdgeOne Pages
        uses: TencentEdgeOne/edgeone-pages-action@v1
        with:
          token: ${{ secrets.EDGEONE_API_TOKEN }}
          project-name: "onegzus"
          directory: "apps/mobile_web/web"
