name: Deploy to EdgeOne Pages
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EdgeOne Pages
        run: npx edgeone makers deploy apps/mobile_web/web -n onegzus-overseas -t "${{ secrets.EDGEONE_API_TOKEN }}" -e production -a overseas
